### ISSUE TITLE
mtime-mismatch modal

### ISSUE THREAD

**Issue by lincolnbrito** [Dragontek/octobercms#3]
When I update a static page for second time it show a modal with message: mtime-mismatch.

**Comment by jmondragon** [comment]
Thank you, is this with the Static Pages plugin, or directly through the CMS?

**Comment by lincolnbrito** [comment]
Directly through the CMS

**Comment by jmondragon** [comment]
I can't seem to duplicate this error.  Could you give me a little bit more information on your setup?

Are you using Docker for Windows/Mac?  Are you mounting the volume locally?  Is this on a clean install, or do you have plugins installed?

Thank you,
Josh

**Comment by jcorapi** [comment]
I'm getting the same thing, but it's happening when I add a 2 of the same components to a page.

**Comment by jcorapi** [comment]
I refreshed the page....No longer getting the error. 

I think the reason I received this error is because I might have updated the page, then uploaded it to the server.  But on the backend I was still working with the older version.

**Comment by jmondragon** [comment]
I'm going to close this one as an upstream bug octobercms/october#2690.  

It appears to be fixed in release 412 of October.
