### ISSUE TITLE
Container requires restart to persist. On first run, it configures and quits.

### ISSUE THREAD

**Issue by acoard** [Dragontek/octobercms#9]
**Current Behaviour**:

When running `docker run...` on the image the very first time, it runs the configuration entrypoint script and then stops.  The docker container itself halts, and apache2-forward is not called (or at least does not keep the container alive).  However, if you run `docker start` on on the halted container, then it calls apache2-forward properly and persists.

**Desired Behaviour**:

Only have to run `docker run...` once, it configures the then immediately starts up apache2-forward and persists normally.

**Details**:

This is using 7.1-apache

----

Thanks for the image, really appreciate it, all the configuration options seem perfect for me.

If this is working as intended please just let me know. I definitely see the benefit of using the configuration script in general, it'd just be nice if it fired up the server after right away.  Cheers.

**Comment by acoard** [comment]
Update - I can get the desired behaviour if I modify my run command to include:
```
-e "OCTOBER_CMS_DISABLE_CORE_UPDATES=true"
```

Considering I want to disable these regardless, I can say this effectively deals with the issue for me.

Feel free to close the issue, but I'll leave it open just to bring the issue to your attention.

Cheers.

**Comment by jmondragon** [comment]
Thank you for your report and follow-up.  I will take a look and leave this open, because it should work even with core updates enabled.

**Comment by jmondragon** [comment]
I've removed the automatic update from `docker-entrypoint.sh`
